version: '2'
services:
proxy:
# You might want to use a proper version
image: traefik
command: --configFile=/traefik.toml
restart: unless-stopped
# Here's the network we created:
networks:
- web
# The traefik entryPoints
ports:
- 80:80
- 443:443
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.example.com
# Traefik will proxy to its own GUI.
      - traefik.port=8080
- traefik.docker.network=web
    volumes: 
- /var/run/docker.sock:/var/run/docker.sock 
- /opt/traefik/traefik.toml:/traefik.toml 
- /opt/traefik/acme.json:/acme.json 
networks: 
web: 
external: true 
