version: '2.1'

volumes:
  apps:
  config:
  data:
  db:

services:
  app:
    image: nextcloud:14
    restart: always
    depends_on:
      - db
    volumes:
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password #changme
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password #changeme
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.example.com #changeme
    networks:
      - web
      - local
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:nextcloud.example.com #changeme
      - traefik.port=80
      - traefik.docker.network=web

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password #changeme
      - MYSQL_PASSWORD=password #changeme
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - local

networks:
  web:
    external: true
  local:
