version: '3'
services:
  lychee:
    image: kolex/lychee:3.1.6
    container_name: lychee
    restart: unless-stopped
    networks:
      - web
      - internal
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:lychee.example.com #changeme
      - traefik.port=80
      - traefik.docker.network=web
    volumes:
      - config:/var/www/html/data
      - images:/var/www/html/uploads

  db:
    image: mariadb
    container_name: lychee_db
    restart: unless-stopped
    networks:
     - internal
    volumes:
     - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password #changeme
      MYSQL_DATABASE: lychee
      MYSQL_USER: lychee
      MYSQL_PASSWORD: password #changeme

networks:
  web:
    external: true
  internal:

volumes:
  config:
  images:
db: